apiVersion: v1
kind: Service
metadata:
  name: javaapi
  labels:
    app: javaapi
spec:
  selector:
    app: javaapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.javaapi.port }}
  type: ClusterIP