apiVersion: v1
kind: Service
metadata:
  name: reactui
  labels:
    app: reactui
spec:
  selector:
    app: reactui
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.reactui.port }}
  type: ClusterIP