apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-services-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: app-services-group
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80, "HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-2:582683034382:certificate/9525c53b-6f25-44e2-9863-7c262f92deda
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/load-balancer-attributes: access_logs.s3.enabled=true,access_logs.s3.bucket=alb-logs,access_logs.s3.prefix=app-services
    alb.ingress.kubernetes.io/inbound-cidrs: 10.0.0.0/8
    kubernetes.io/ingress.class: alb
    external-dns.alpha.kubernetes.io/hostname: internal-alb.core.dcli.com
spec:
  rules:
    - host: internal-alb.core.dcli.com
      http:
        paths:
          - path: /java
            pathType: Prefix
            backend:
              service:
                name: javaapi
                port:
                  number: 80
          - path: /react
            pathType: Prefix
            backend:
              service:
                name: react-ui
                port:
                  number: 80
          - path: /node
            pathType: Prefix
            backend:
              service:
                name: nodeapi
                port:
                  number: 80
  tls:
    - hosts:
        - internal-alb.core.dcli.com
      secretName: dummy-tls-secret
