apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-services-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.certificateArn }}
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/actions.ssl-redirect: >
      {"Type":"redirect","RedirectConfig":{"Protocol":"HTTPS","Port":"443","StatusCode":"HTTP_301"}}
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/inbound-cidrs: 10.0.0.0/8
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.domainName }}
spec:
  rules:
    - host: {{ .Values.domainName }}
      http:
        paths:
          - path: /javaapi
            pathType: Prefix
            backend:
              service:
                name: javaapi
                port:
                  number: 80
          - path: /nodeapi
            pathType: Prefix
            backend:
              service:
                name: nodeapi
                port:
                  number: 80
          - path: /reactui
            pathType: Prefix
            backend:
              service:
                name: reactui
                port:
                  number: 80