apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-ui
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-ui
  template:
    metadata:
      labels:
        app: react-ui
    spec:
      containers:
      - name: react-ui
        image: {{ .Values.reactui.image }}
        ports:
        - containerPort: {{ .Values.reactui.port }}
